name = "central-auth-broker"
main = "src/index.ts"
compatibility_date = "2026-07-23"
account_id = "314e7e015b5f4429c4e2da1e6ec93271"
workers_dev = false

routes = [
  { pattern = "broker.jsmunro.me/*", zone_name = "jsmunro.me" }
]

kv_namespaces = [
  { binding = "AUTH_TOKENS", id = "ef17d3c055e34a8699a596d47878e44c" }
]

[triggers]
crons = ["*/30 * * * *"]

[vars]
BROKER_URL = "https://broker.jsmunro.me"
CLOUDFLARE_OAUTH_SCOPES = "access-acct.read access-acct.revoke access-acct.write access-app.read access-app.revoke access-app.write access-audit-log.read access-certificate.read access-certificate.write access-custom-page.read access-custom-page.write access-device-posture.read access-device-posture.write access-group.read access-group.write access-idp.read access-idp.write access-key.read access-key.write access-org.read access-org.revoke access-org.write access-policy-test.read access-policy-test.write access-policy.read access-policy.write access-population.read access-population.write access-saml-certificate.read access-saml-certificate.write access-scim-log.read access-seats.write access-service-token.read access-service-token.write access-ssh-auditing.read access-ssh-auditing.write access-tag.read access-tag.write access-users.read access-users.write access.read access.revoke access.write account-analytics.read account-logs.read account-settings.read aig.metadata_read aig.read aig.run aig.write analytics.read argotunnel.read argotunnel.write casb.read casb.write d1.metadata_read d1.read d1.write dls.read dls.write dns.read dns.write logs.read memberships.read offline_access teams-cds-compute-account.read teams-cds-compute-account.write teams-connector-cloudflared.monitoring teams-connector-cloudflared.read teams-connector-cloudflared.write teams-connector-warp.read teams-connector-warp.write teams-connectors.read teams-connectors.write teams-dex.read teams-dex.write teams-networks.read teams-networks.write teams-pii.read teams-resilience.read teams-resilience.write teams-secure.location teams.read teams.report teams.write user-details.read workers-kv-storage.metadata_read workers-kv-storage.read workers-kv-storage.write workers-observability.read workers-r2-bucket-item.read workers-r2-bucket-item.write workers-r2.metadata_read workers-r2.read workers-r2.write workers-routes.read workers-routes.write workers-scripts.read workers-scripts.write workers-tail.read zone-access.read zone-access.revoke zone-access.write zone-settings.read zone-settings.write zone.read zone.write"
ACCESS_TEAM_DOMAIN = "jsmunro.cloudflareaccess.com"
ACCESS_AUD = "8912bf9e72b6893335dd32ab794eb7b7399d7a554b4bcf7a1ca3c04be49cf6ab"
ENVIRONMENT = "production"
